# generated by datamodel-codegen:
#   filename:  schemas

from __future__ import annotations

from .bundle_schema import (
    Bundle,
    HoldForWillCall,
    PairRiders,
    Predicted,
    ReassignVehicle,
    RequestExtraCapacity,
    ResequenceRoute,
    ShiftChairStart,
    ShiftPickupWindow,
    SwapChairs,
)
from .common_schema import Audience, Common, Load, Mobility, ReasonCode, ShiftId, Side, Window, Zone
from .event_schema import Event, EventType
from .explanation_schema import Explanation, NewTimes
from .fleet_schema import Fleet, Vehicle, VehicleStatus
from .judge_score_schema import JudgeScore, JudgeScores
from .ledger_entry_schema import Actor, LedgerEntry, Usage
from .manifest_schema import Leg, Manifest, Route, RouteStop, StopKind, Trip, TripStatus
from .metrics_schema import Metrics
from .review_item_schema import ReviewItem
from .roster_schema import (
    Patient,
    Provider,
    RecoveryBufferMin,
    Rider,
    Roster,
    RxDays,
    RxDurationMin,
)
from .rules_schema import (
    AutonomyLevel,
    BrokerRules,
    DwellMin,
    RecoveryBuffer,
    Rules,
    ShiftWindows,
    StopRules,
    SynthRules,
    UnitRules,
    VanCapacity,
    Weights,
)
from .travel_schema import Node, Travel
from .unit_schema import Chair, Shift, StationType, Unit
from .verify_result_schema import VerifyResult, Violation, ViolationCode

__all__ = [
    "Actor",
    "Audience",
    "AutonomyLevel",
    "BrokerRules",
    "Bundle",
    "Chair",
    "Common",
    "DwellMin",
    "Event",
    "EventType",
    "Explanation",
    "Fleet",
    "HoldForWillCall",
    "JudgeScore",
    "JudgeScores",
    "LedgerEntry",
    "Leg",
    "Load",
    "Manifest",
    "Metrics",
    "Mobility",
    "NewTimes",
    "Node",
    "PairRiders",
    "Patient",
    "Predicted",
    "Provider",
    "ReasonCode",
    "ReassignVehicle",
    "RecoveryBuffer",
    "RecoveryBufferMin",
    "RequestExtraCapacity",
    "ResequenceRoute",
    "ReviewItem",
    "Rider",
    "Roster",
    "Route",
    "RouteStop",
    "Rules",
    "RxDays",
    "RxDurationMin",
    "Shift",
    "ShiftChairStart",
    "ShiftId",
    "ShiftPickupWindow",
    "ShiftWindows",
    "Side",
    "StationType",
    "StopKind",
    "StopRules",
    "SwapChairs",
    "SynthRules",
    "Travel",
    "Trip",
    "TripStatus",
    "Unit",
    "UnitRules",
    "Usage",
    "VanCapacity",
    "Vehicle",
    "VehicleStatus",
    "VerifyResult",
    "Violation",
    "ViolationCode",
    "Weights",
    "Window",
    "Zone",
]
