# generated by datamodel-codegen:
#   filename:  bundle.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint, constr

from . import common_schema


class Predicted(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    delta_wait_min: int
    delta_early_min: int
    chair_changes: conint(ge=0)
    consent_moves: conint(ge=0)
    vehicle_min: int


class RequestExtraCapacity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["request_extra_capacity"]
    vehicle_min: conint(ge=0)
    reason: str


class ShiftChairStart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["shift_chair_start"]
    patient_id: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])$") = Field(..., title="PatientId")
    delta_min: int


class SwapChairs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["swap_chairs"]
    patient_a: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])$") = Field(..., title="PatientId")
    patient_b: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])$") = Field(..., title="PatientId")


class ShiftPickupWindow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["shift_pickup_window"]
    trip_id: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])[tf]$") = Field(..., title="TripId")
    delta_min: int


class ReassignVehicle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["reassign_vehicle"]
    trip_id: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])[tf]$") = Field(..., title="TripId")
    vehicle_id: constr(pattern=r"^V[1-5]$") = Field(..., title="VehicleId")


class ResequenceRoute(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["resequence_route"]
    vehicle_id: constr(pattern=r"^V[1-5]$") = Field(..., title="VehicleId")
    trip_ids: list[constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])[tf]$")]


class PairRiders(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["pair_riders"]
    trip_ids: list[constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])[tf]$")]
    vehicle_id: constr(pattern=r"^V[1-5]$") = Field(..., title="VehicleId")


class HoldForWillCall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["hold_for_will_call"]
    trip_id: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])[tf]$") = Field(..., title="TripId")
    reason: str


class Bundle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    bundle_id: str
    side: common_schema.Side
    moves: list[
        ShiftChairStart
        | SwapChairs
        | ShiftPickupWindow
        | ReassignVehicle
        | ResequenceRoute
        | PairRiders
        | RequestExtraCapacity
        | HoldForWillCall
    ]
    predicted: Predicted
    touches: list[constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])$")]
    notes_relevant: list[str]
