# generated by datamodel-codegen:
#   filename:  common.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Common(RootModel[Any]):
    root: Any = Field(..., title="Common")


class Window(RootModel[list[constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$")]]):
    root: list[constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$")] = Field(
        ..., max_length=2, min_length=2, title="Window"
    )


class Mobility(StrEnum):
    ambulatory = "ambulatory"
    assist = "assist"
    wheelchair = "wheelchair"
    stretcher = "stretcher"


class Side(StrEnum):
    unit = "unit"
    broker = "broker"
    both = "both"


class ReasonCode(StrEnum):
    NO_FEASIBLE_WINDOW = "NO_FEASIBLE_WINDOW"
    STRETCHER = "STRETCHER"
    CONSENT_BLOCK = "CONSENT_BLOCK"
    BROKER_POLICY = "BROKER_POLICY"
    CLINICAL_NOTE = "CLINICAL_NOTE"


class Audience(StrEnum):
    rider = "rider"
    nurse = "nurse"
    dispatcher = "dispatcher"


class Load(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ambulatory: conint(ge=0)
    wheelchair: conint(ge=0)
    stretcher: conint(ge=0)


class Zone(StrEnum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"


class ShiftId(StrEnum):
    S1 = "S1"
    S2 = "S2"
    S3 = "S3"
