# generated by datamodel-codegen:
#   filename:  event.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr


class EventType(StrEnum):
    vehicle_down = "vehicle_down"
    chair_down = "chair_down"
    late_arrival = "late_arrival"
    add_on_patient = "add_on_patient"
    travel_slowdown = "travel_slowdown"


class Event(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    t: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") = Field(..., title="Time")
    type: EventType = Field(..., title="EventType")
    payload: dict[str, Any]
