# generated by datamodel-codegen:
#   filename:  explanation.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, constr

from . import common_schema


class NewTimes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    chair_start: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") | None
    pickup_window: common_schema.Window | None


class Explanation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    audience: common_schema.Audience
    subject_id: str
    what_changed: str
    why: str
    new_times: NewTimes
    ledger_refs: list[str]
    contact: str
    reading_grade: float
