# generated by datamodel-codegen:
#   filename:  fleet.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint, constr

from . import common_schema


class VehicleStatus(StrEnum):
    ok = "ok"
    down = "down"


class Vehicle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    vehicle_id: constr(pattern=r"^V[1-5]$") = Field(..., title="VehicleId")
    cap_ambulatory: conint(ge=0)
    cap_wheelchair: conint(ge=0)
    cap_stretcher: conint(ge=0)
    shift: common_schema.Window
    depot_node: conint(ge=0, le=39) = Field(..., title="NodeId")
    status: VehicleStatus = Field(..., title="VehicleStatus")


class Fleet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    synthetic: Literal[True]
    generator: str
    seed: int
    vehicles: list[Vehicle]
