# generated by datamodel-codegen:
#   filename:  judge_score.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, conint


class JudgeScores(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    accuracy: conint(ge=0, le=2)
    actionable: conint(ge=0, le=2)
    plain: conint(ge=0, le=2)
    tone: conint(ge=0, le=2)
    complete: conint(ge=0, le=2)
    safe: conint(ge=0, le=2)


class JudgeScore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    explanation_id: str
    scores: JudgeScores
    rationale: str
    pass_: bool = Field(..., alias="pass")
