# generated by datamodel-codegen:
#   filename:  ledger_entry.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, confloat, conint


class Actor(StrEnum):
    model = "model"
    tool = "tool"
    human = "human"


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input: conint(ge=0)
    cache_read: conint(ge=0)
    cache_write: conint(ge=0)
    output: conint(ge=0)


class LedgerEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ts: str
    run_id: str
    git_sha: str
    iteration: conint(ge=0)
    actor: Actor = Field(..., title="Actor")
    event: str
    payload: dict[str, Any]
    model_id: str
    effort: str
    prompt_versions: dict[str, int]
    usage: Usage
    cost_usd: confloat(ge=0.0)
    input_hashes: dict[str, str]
