# generated by datamodel-codegen:
#   filename:  manifest.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint, constr

from . import common_schema


class Leg(StrEnum):
    to = "to"
    from_ = "from"


class TripStatus(StrEnum):
    scheduled = "scheduled"
    will_call = "will_call"
    queued = "queued"


class Trip(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trip_id: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])[tf]$") = Field(..., title="TripId")
    rider_id: constr(pattern=r"^R(0[1-9]|1\d|2[0-2])$") = Field(..., title="RiderId")
    leg: Leg = Field(..., title="Leg")
    origin_node: conint(ge=0, le=39) = Field(..., title="NodeId")
    dest_node: conint(ge=0, le=39) = Field(..., title="NodeId")
    requested_time: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") = Field(..., title="Time")
    window: common_schema.Window | None
    vehicle_id: constr(pattern=r"^V[1-5]$") | None
    seq: conint(ge=0) | None
    status: TripStatus = Field(..., title="TripStatus")


class StopKind(StrEnum):
    pickup = "pickup"
    dropoff = "dropoff"


class RouteStop(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trip_id: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])[tf]$") = Field(..., title="TripId")
    kind: StopKind = Field(..., title="StopKind")
    node: conint(ge=0, le=39) = Field(..., title="NodeId")
    eta: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") = Field(..., title="Time")
    load_after: common_schema.Load


class Route(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    vehicle_id: constr(pattern=r"^V[1-5]$") = Field(..., title="VehicleId")
    stops: list[RouteStop]


class Manifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    synthetic: Literal[True]
    generator: str
    seed: int
    broker_policy_text: str
    trips: list[Trip]
    routes: list[Route]
