# generated by datamodel-codegen:
#   filename:  metrics.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, confloat, conint


class Metrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    mean_post_wait: float
    p90_post_wait: float
    wait_min_total: float
    early_wait_mean: float
    within_30_share: confloat(ge=0.0, le=1.0)
    conflicts: conint(ge=0)
    equity_gap: float
    vehicle_min: float
    riders_flagged: conint(ge=0)
