# generated by datamodel-codegen:
#   filename:  review_item.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import common_schema


class ReviewItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    item_id: str
    subject: str
    reason_code: common_schema.ReasonCode
    what_was_tried: list[str]
    recommended_action: str
    draft_message: str
    owner: str
    urgency: str
