# generated by datamodel-codegen:
#   filename:  roster.schema.json

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint, constr

from . import common_schema


class RxDays(StrEnum):
    MWF = "MWF"
    TTS = "TTS"


class RxDurationMin(IntEnum):
    integer_210 = 210
    integer_225 = 225
    integer_240 = 240
    integer_255 = 255
    integer_270 = 270


class RecoveryBufferMin(IntEnum):
    integer_20 = 20
    integer_35 = 35


class Patient(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    patient_id: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])$") = Field(..., title="PatientId")
    display_name: str
    rx_days: RxDays = Field(..., title="RxDays")
    rx_duration_min: RxDurationMin = Field(..., title="RxDurationMin")
    shift_id: common_schema.ShiftId
    chair_id: constr(pattern=r"^C(0[1-9]|1[0-2])$") = Field(..., title="ChairId")
    start_time: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") = Field(..., title="Time")
    clinically_fixed: bool
    fixed_reason: str | None
    consent_to_move: bool
    mobility: common_schema.Mobility
    recovery_buffer_min: RecoveryBufferMin = Field(..., title="RecoveryBufferMin")
    nurse_note: str
    moves_this_week: conint(ge=0)
    rider_id: constr(pattern=r"^R(0[1-9]|1\d|2[0-2])$") | None
    late_start_min: conint(ge=0)
    runover_min: conint(ge=0)


class Provider(StrEnum):
    broker = "broker"
    family = "family"


class Rider(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rider_id: constr(pattern=r"^R(0[1-9]|1\d|2[0-2])$") = Field(..., title="RiderId")
    patient_id: constr(pattern=r"^P(0[1-9]|[12]\d|3[0-6])$") = Field(..., title="PatientId")
    home_node: conint(ge=0, le=39) = Field(..., title="NodeId")
    language: str
    caregiver_window: common_schema.Window | None
    rider_note: str
    provider: Provider = Field(..., title="Provider")


class Roster(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    synthetic: Literal[True]
    generator: str
    seed: int
    patients: list[Patient]
    riders: list[Rider]
