# generated by datamodel-codegen:
#   filename:  rules.schema.json

from __future__ import annotations

from enum import IntEnum

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr

from . import common_schema


class AutonomyLevel(IntEnum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2


class ShiftWindows(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    S1: common_schema.Window
    S2: common_schema.Window
    S3: common_schema.Window


class RecoveryBuffer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    default: conint(ge=0)
    hypotension: conint(ge=0)


class DwellMin(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ambulatory: conint(ge=0)
    assist: conint(ge=0)
    wheelchair: conint(ge=0)
    stretcher: conint(ge=0)


class VanCapacity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    standard: common_schema.Load
    lift: common_schema.Load


class Weights(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    post_wait: float
    early_wait: float
    chair_change: float
    consent_move: float
    vehicle_min: float
    review_item: float


class StopRules(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min_improvement_pct: confloat(ge=0.0)
    max_iterations: conint(ge=1)
    max_wall_s: confloat(ge=1.0)
    target_post_wait: confloat(ge=0.0)
    target_equity_gap: confloat(ge=0.0)


class SynthRules(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    runover_share: confloat(ge=0.0, le=1.0)
    runover_max_min: conint(ge=0)
    late_start_share: confloat(ge=0.0, le=1.0)
    late_start_min: conint(ge=0)
    late_start_max: conint(ge=0)
    extra_stops_share: confloat(ge=0.0, le=1.0)
    extra_stops_max: conint(ge=0)
    will_call_count: conint(ge=0)
    will_call_delay_min: conint(ge=0)
    standing_order_offset_min: conint(ge=0)


class UnitRules(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    turnover_min: conint(ge=0)
    stagger_cohort_size: conint(ge=1)
    stagger_step_min: conint(ge=1)
    max_chair_changes_per_shift: conint(ge=0)
    max_chair_shift_min: conint(ge=0)
    close_time: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") = Field(..., title="Time")
    shifts: ShiftWindows


class BrokerRules(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ada_negotiation_min: conint(ge=0)
    pickup_window_min: conint(ge=1)
    earliest_pickup: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") = Field(..., title="Time")
    driver_wait_min: conint(ge=0)
    max_ride_min: conint(ge=1)
    max_ride_ratio: confloat(ge=1.0)
    vehicle_shift: common_schema.Window
    dwell_min: DwellMin
    van_capacity: VanCapacity


class Rules(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unit: UnitRules
    recovery_buffer_min: RecoveryBuffer
    broker: BrokerRules
    weights: Weights
    stop: StopRules
    autonomy_level: AutonomyLevel
    max_moves_per_bundle: conint(ge=1)
    max_moves_per_patient_per_week: conint(ge=0)
    synth: SynthRules
