# generated by datamodel-codegen:
#   filename:  travel.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint

from . import common_schema


class Node(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    node_id: conint(ge=0, le=39) = Field(..., title="NodeId")
    zone: common_schema.Zone
    x: float
    y: float


class Travel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    synthetic: Literal[True]
    generator: str
    seed: int
    nodes: list[Node]
    matrix: list[list[conint(ge=0)]]
