# generated by datamodel-codegen:
#   filename:  unit.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint, constr

from . import common_schema


class StationType(StrEnum):
    standard = "standard"
    isolation = "isolation"


class Chair(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    chair_id: constr(pattern=r"^C(0[1-9]|1[0-2])$") = Field(..., title="ChairId")
    station_type: StationType = Field(..., title="StationType")
    available_windows: list[common_schema.Window]


class Shift(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    shift_id: common_schema.ShiftId
    putton_start: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") = Field(..., title="Time")
    putton_end: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") = Field(..., title="Time")


class Unit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    synthetic: Literal[True]
    generator: str
    seed: int
    unit_id: str
    name: str
    chairs: list[Chair]
    shifts: list[Shift]
    stagger_cohort_size: conint(ge=1)
    stagger_step_min: conint(ge=1)
    turnover_min: conint(ge=0)
    close_time: constr(pattern=r"^([01]\d|2[0-3]):[0-5]\d$") = Field(..., title="Time")
    policy_text: str
